site_name: Buson
site_description: Documentacao do projeto Buson - Engenharia de Dados 
site_url: https://github.com/thiagoDimon/buson-bd-eng-dados
site_favicon: images/busOnFonteBranca.png
site_logo: images/busOnFonteBranca.png
site_keywords: Engenharia de Dados, Engenharia de Software, SATC, Python, Pyspark, Delta, Jupyter, Git, GitHub, Markdown, MkDocs, Material Theme

repo_name: buson-bd-eng-dados
repo_url: https://github.com/thiagoDimon/buson-bd-eng-dados
edit_uri: edit/master/docs/

docs_dir: docs

theme:
  name: material
  
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: black
      accent: yellow
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: yellow
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
    
  logo: images/busOnFonteBranca.png 

  language: pt
  features:
    - navigation.footer
    - navigation.tabs.sticky
    - navigation.path
    #- navigation.paging
    #- navigation.expand
    - navigation.top
    #- navigation.sidebar
    - navigation.next-prev
    #- navigation.toc
    #- navigation.scrollspy
    - search.highlight
    - search.suggest
  icon:
    repo: fontawesome/brands/github

hide:
  - search
  - navigation
  - toc

extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/thiagoDimon/buson-bd-eng-dados
  generator: false

copyright: Copyright &copy; 2024 - <a href="#" target="_blank"><b>Buson</b></a> - Todos os direitos reservados.

plugins:
  - search
  

markdown_extensions: 
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html

# Customization options
extra_css:
  - 'css/extra.css'  # Path to your custom CSS

nav:
  - Início: index.md
  - Pré-Requisitos: preRequisitos.md
  - Configurações Docker: configuracoesDocker.md
  - Geração de Dados: geracaoDados.md
  - Inicializando: inicializando.md
  - Configurações Airflow: configuracoesAirflow.md
  - Pipeline: executando.md
  - Dashboard: dashboard.md
