version: '3.9'

services:
  buson-bd-eng-dados:
    container_name: 'postgres-buson-bd-eng-dados'
    image: postgres:16.1
    ports:
      - 1111:5432
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
          - ./BusonDB:/var/lib/postgresql/data
          - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d