FROM quay.io/astronomer/astro-runtime:11.5.0

RUN pip install minio
# RUN pip install install-jdk
# RUN export JAVA_HOME='/usr/lib/jvm/java-8-openjdk-amd64'
# RUN pip install pyspark
# RUN export PATH=$PATH:$JAVA_HOME/bin
# RUN pip install apache-airflow-providers-apache-spark
# RUN pip install apache-airflow-providers-cncf-kubernetes
# RUN sudo apt install default-jdk